### ISSUE TITLE
Data export functionality (feature request)

### ISSUE THREAD

**Issue by vervalkon** [RayCarrot/GBAC#2]
The information shown in the leftmost panel's table is extremely valuable, it would be very useful to be able to export it as CSV or even as a TXT.
Finding data addresses and their compression methods with this tool is great, but it is useless to me (as a hacker/programmer) if I can't use the data. It would be very helpful to get the address list in textual form.

**Comment by RayCarrot** [comment]
Just added in latest release now!
https://github.com/RayCarrot/GBAC/releases/tag/1.2.0.0

**Comment by vervalkon** [comment]
Thank you **very** much!!
